const playingCards = [
	{
		id: 0,
		rank: "2",
		points: 2,
		suit: "hearts",
		img: "public/img/cards/2_of_hearts.png",
	},
	{
		id: 1,
		rank: "3",
		points: 3,
		suit: "hearts",
		img: "public/img/cards/3_of_hearts.png",
	},
	{
		id: 2,
		rank: "4",
		points: 4,
		suit: "hearts",
		img: "public/img/cards/4_of_hearts.png",
	},
	{
		id: 3,
		rank: "5",
		points: 5,
		suit: "hearts",
		img: "public/img/cards/5_of_hearts.png",
	},
	{
		id: 4,
		rank: "6",
		points: 6,
		suit: "hearts",
		img: "public/img/cards/6_of_hearts.png",
	},
	{
		id: 5,
		rank: "7",
		points: 7,
		suit: "hearts",
		img: "public/img/cards/7_of_hearts.png",
	},
	{
		id: 6,
		rank: "8",
		points: 8,
		suit: "hearts",
		img: "public/img/cards/8_of_hearts.png",
	},
	{
		id: 7,
		rank: "9",
		points: 9,
		suit: "hearts",
		img: "public/img/cards/9_of_hearts.png",
	},
	{
		id: 8,
		rank: "A",
		points: 11,
		suit: "hearts",
		img: "public/img/cards/ace_of_hearts.png",
	},
	{
		id: 9,
		rank: "A",
		points: 11,
		suit: "hearts",
		img: "public/img/cards/ace_of_hearts.png",
	},
	{
		id: 10,
		rank: "A",
		points: 11,
		suit: "hearts",
		img: "public/img/cards/ace_of_hearts.png",
	},
	{
		id: 11,
		rank: "A",
		points: 11,
		suit: "hearts",
		img: "public/img/cards/ace_of_hearts.png",
	},
	{
		id: 12,
		rank: "A",
		points: 11,
		suit: "hearts",
		img: "public/img/cards/ace_of_hearts.png",
	},
	{
		id: 13,
		rank: "2",
		points: 2,
		suit: "diamonds",
		img: "public/img/cards/2_of_diamonds.png",
	},
	{
		id: 14,
		rank: "3",
		points: 3,
		suit: "diamonds",
		img: "public/img/cards/3_of_diamonds.png",
	},
	{
		id: 15,
		rank: "4",
		points: 4,
		suit: "diamonds",
		img: "public/img/cards/4_of_diamonds.png",
	},
	{
		id: 16,
		rank: "5",
		points: 5,
		suit: "diamonds",
		img: "public/img/cards/5_of_diamonds.png",
	},
	{
		id: 17,
		rank: "6",
		points: 6,
		suit: "diamonds",
		img: "public/img/cards/6_of_diamonds.png",
	},
	{
		id: 18,
		rank: "7",
		points: 7,
		suit: "diamonds",
		img: "public/img/cards/7_of_diamonds.png",
	},
	{
		id: 19,
		rank: "8",
		points: 8,
		suit: "diamonds",
		img: "public/img/cards/8_of_diamonds.png",
	},
	{
		id: 20,
		rank: "9",
		points: 9,
		suit: "diamonds",
		img: "public/img/cards/9_of_diamonds.png",
	},
	{
		id: 21,
		rank: "A",
		points: 11,
		suit: "hearts",
		img: "public/img/cards/ace_of_hearts.png",
	},
	{
		id: 22,
		rank: "A",
		points: 11,
		suit: "hearts",
		img: "public/img/cards/ace_of_hearts.png",
	},
	{
		id: 23,
		rank: "A",
		points: 11,
		suit: "hearts",
		img: "public/img/cards/ace_of_hearts.png",
	},
	{
		id: 24,
		rank: "K",
		points: 10,
		suit: "diamonds",
		img: "public/img/cards/king_of_diamonds.png",
	},
	{
		id: 25,
		rank: "A",
		points: 11,
		suit: "diamonds",
		img: "public/img/cards/ace_of_diamonds.png",
	},
	{
		id: 26,
		rank: "2",
		points: 2,
		suit: "clubs",
		img: "public/img/cards/2_of_clubs.png",
	},
	{
		id: 27,
		rank: "3",
		points: 3,
		suit: "clubs",
		img: "public/img/cards/3_of_clubs.png",
	},
	{
		id: 28,
		rank: "4",
		points: 4,
		suit: "clubs",
		img: "public/img/cards/4_of_clubs.png",
	},
	{
		id: 29,
		rank: "5",
		points: 5,
		suit: "clubs",
		img: "public/img/cards/5_of_clubs.png",
	},
	{
		id: 30,
		rank: "6",
		points: 6,
		suit: "clubs",
		img: "public/img/cards/6_of_clubs.png",
	},
	{
		id: 31,
		rank: "7",
		points: 7,
		suit: "clubs",
		img: "public/img/cards/7_of_clubs.png",
	},
	{
		id: 32,
		rank: "8",
		points: 8,
		suit: "clubs",
		img: "public/img/cards/8_of_clubs.png",
	},
	{
		id: 33,
		rank: "9",
		points: 9,
		suit: "clubs",
		img: "public/img/cards/9_of_clubs.png",
	},
	{
		id: 34,
		rank: "10",
		points: 10,
		suit: "clubs",
		img: "public/img/cards/10_of_clubs.png",
	},
	{
		id: 35,
		rank: "J",
		points: 10,
		suit: "clubs",
		img: "public/img/cards/jack_of_clubs.png",
	},
	{
		id: 36,
		rank: "Q",
		points: 10,
		suit: "clubs",
		img: "public/img/cards/queen_of_clubs.png",
	},
	{
		id: 37,
		rank: "K",
		points: 10,
		suit: "clubs",
		img: "public/img/cards/king_of_clubs.png",
	},
	{
		id: 38,
		rank: "A",
		points: 11,
		suit: "clubs",
		img: "public/img/cards/ace_of_clubs.png",
	},
	{
		id: 39,
		rank: "2",
		points: 2,
		suit: "spades",
		img: "public/img/cards/2_of_spades.png",
	},
	{
		id: 40,
		rank: "3",
		points: 3,
		suit: "spades",
		img: "public/img/cards/3_of_spades.png",
	},
	{
		id: 41,
		rank: "4",
		points: 4,
		suit: "spades",
		img: "public/img/cards/4_of_spades.png",
	},
	{
		id: 42,
		rank: "5",
		points: 5,
		suit: "spades",
		img: "public/img/cards/5_of_spades.png",
	},
	{
		id: 43,
		rank: "6",
		points: 6,
		suit: "spades",
		img: "public/img/cards/6_of_spades.png",
	},
	{
		id: 44,
		rank: "7",
		points: 7,
		suit: "spades",
		img: "public/img/cards/7_of_spades.png",
	},
	{
		id: 45,
		rank: "8",
		points: 8,
		suit: "spades",
		img: "public/img/cards/8_of_spades.png",
	},
	{
		id: 46,
		rank: "9",
		points: 9,
		suit: "spades",
		img: "public/img/cards/9_of_spades.png",
	},
	{
		id: 47,
		rank: "10",
		points: 10,
		suit: "spades",
		img: "public/img/cards/10_of_spades.png",
	},
	{
		id: 48,
		rank: "J",
		points: 10,
		suit: "spades",
		img: "public/img/cards/jack_of_spades.png",
	},
	{
		id: 49,
		rank: "Q",
		points: 10,
		suit: "spades",
		img: "public/img/cards/queen_of_spades.png",
	},
	{
		id: 50,
		rank: "K",
		points: 10,
		suit: "spades",
		img: "public/img/cards/king_of_spades.png",
	},
	{
		id: 51,
		rank: "A",
		points: 11,
		suit: "spades",
		img: "public/img/cards/ace_of_spades.png",
	},
];
export default playingCards;
